// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TuProyecto.Data;

#nullable disable

namespace Artistas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250710010646_espect-user")]
    partial class espectuser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Artistas.Models.Artista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("idCategoria")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("idCategoria");

                    b.ToTable("Artistas");
                });

            modelBuilder.Entity("Artistas.Models.CategoriaArtistas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("CategoriaArtistas");
                });

            modelBuilder.Entity("Artistas.Models.Espectaculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdArtista")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioEspc")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdArtista");

                    b.HasIndex("IdUsuarioEspc");

                    b.ToTable("Espectaculos");
                });

            modelBuilder.Entity("Artistas.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Artistas.Models.Artista", b =>
                {
                    b.HasOne("Artistas.Models.Usuario", "Usuario")
                        .WithMany("ArtistasCreados")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Artistas.Models.CategoriaArtistas", "CategoriaArtista")
                        .WithMany("Artistas")
                        .HasForeignKey("idCategoria")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CategoriaArtista");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Artistas.Models.Espectaculo", b =>
                {
                    b.HasOne("Artistas.Models.Artista", "Artista")
                        .WithMany("Espectaculos")
                        .HasForeignKey("IdArtista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Artistas.Models.Usuario", "Usuario")
                        .WithMany("EspectaculosCreados")
                        .HasForeignKey("IdUsuarioEspc")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Artista");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Artistas.Models.Artista", b =>
                {
                    b.Navigation("Espectaculos");
                });

            modelBuilder.Entity("Artistas.Models.CategoriaArtistas", b =>
                {
                    b.Navigation("Artistas");
                });

            modelBuilder.Entity("Artistas.Models.Usuario", b =>
                {
                    b.Navigation("ArtistasCreados");

                    b.Navigation("EspectaculosCreados");
                });
#pragma warning restore 612, 618
        }
    }
}
